### PR TITLE
Add emoji component

### PR DESCRIPTION
**Pull request by maxwofford**

### CODE REVIEW

**Comment by maxwofford** [comment]
@zachlatta: This uses Slack's method of naming emojis instead of directly using emoji in our code (`:smiley_face:` instead of `😊`). It would be helpful to contributors without emoji support on their system.

**Comment by maxwofford** [comment]
@zachlatta This is ready for review. Here's a few shots:

screenshot_2016-10-30_22 36 37
screenshot_2016-10-30_22 36 30
screenshot_2016-10-30_22 36 26
screenshot_2016-10-30_22 36 06
screenshot_2016-10-30_22 35 52



On a side note, I noticed the submit button on `/cloud9_setup` has issues updating it's background color (there was a strange delay to it). I don't think it's related to this PR, so I'm going to open a new issue for it.

**Comment by maxwofford** [comment]
Issue opened at https://github.com/hackclub/frontend/issues/6

**Comment by zachlatta** [comment]
Looking good. Can you add all of the emoji to this PR?

**Comment by zachlatta** [comment]
(even ones that aren't used)

**Comment by maxwofford** [comment]
@zachlatta Just added it!

1daw33

**Comment by maxwofford** [comment]
Also, let's close #2 when this one is merged.

**Comment by maxwofford** [comment]
@zachlatta Just a quick ping on this.

**Comment by zachlatta** [comment]
Apologies for the delay, adding to my task list for the day.

**Comment by maxwofford** [comment]
Just rebased to update this branch.

**Pull request merged**
